# sampleapi line 5
# sampleapi 2 line 523
# sampleapi 3 line 591

sampleapi = {
    "recipes": [
        {
            "vegetarian": False,
            "vegan": False,
            "glutenFree": False,
            "dairyFree": False,
            "veryHealthy": False,
            "cheap": False,
            "veryPopular": False,
            "sustainable": False,
            "lowFodmap": False,
            "weightWatcherSmartPoints": 7,
            "gaps": "no",
            "preparationMinutes": -1,
            "cookingMinutes": -1,
            "aggregateLikes": 81,
            "healthScore": 0,
            "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
            "license": "CC BY 3.0",
            "sourceName": "Foodista",
            "pricePerServing": 15.1,
            "extendedIngredients": [
                {
                    "id": 18371,
                    "aisle": "Baking",
                    "image": "white-powder.jpg",
                    "consistency": "SOLID",
                    "name": "baking powder",
                    "nameClean": "low sodium baking powder",
                    "original": "1/2 teaspoon baking powder",
                    "originalName": "baking powder",
                    "amount": 0.5,
                    "unit": "teaspoon",
                    "meta": [],
                    "measures": {
                        "us": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons",
                        },
                        "metric": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons",
                        },
                    },
                },
                {
                    "id": 18372,
                    "aisle": "Baking",
                    "image": "white-powder.jpg",
                    "consistency": "SOLID",
                    "name": "baking soda",
                    "nameClean": "baking soda",
                    "original": "1/2 teaspoon baking soda",
                    "originalName": "baking soda",
                    "amount": 0.5,
                    "unit": "teaspoon",
                    "meta": [],
                    "measures": {
                        "us": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons",
                        },
                        "metric": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons",
                        },
                    },
                },
                {
                    "id": 9040,
                    "aisle": "Produce",
                    "image": "bananas.jpg",
                    "consistency": "SOLID",
                    "name": "bananas",
                    "nameClean": "banana",
                    "original": "2 ripe bananas",
                    "originalName": "ripe bananas",
                    "amount": 2.0,
                    "unit": "",
                    "meta": ["ripe"],
                    "measures": {
                        "us": {"amount": 2.0, "unitShort": "", "unitLong": ""},
                        "metric": {"amount": 2.0, "unitShort": "", "unitLong": ""},
                    },
                },
                {
                    "id": 19334,
                    "aisle": "Baking",
                    "image": "light-brown-sugar.jpg",
                    "consistency": "SOLID",
                    "name": "brown sugar",
                    "nameClean": "golden brown sugar",
                    "original": "1/2 cup brown sugar",
                    "originalName": "brown sugar",
                    "amount": 0.5,
                    "unit": "cup",
                    "meta": [],
                    "measures": {
                        "us": {"amount": 0.5, "unitShort": "cups", "unitLong": "cups"},
                        "metric": {
                            "amount": 118.294,
                            "unitShort": "ml",
                            "unitLong": "milliliters",
                        },
                    },
                },
                {
                    "id": 1001,
                    "aisle": "Milk, Eggs, Other Dairy",
                    "image": "butter-sliced.jpg",
                    "consistency": "SOLID",
                    "name": "butter",
                    "nameClean": "butter",
                    "original": "1 Tbs. - Soft Butter",
                    "originalName": "Soft Butter",
                    "amount": 1.0,
                    "unit": "Tbs",
                    "meta": ["soft"],
                    "measures": {
                        "us": {"amount": 1.0, "unitShort": "Tbs", "unitLong": "Tb"},
                        "metric": {"amount": 1.0, "unitShort": "Tbs", "unitLong": "Tb"},
                    },
                },
                {
                    "id": 10019146,
                    "aisle": "Baking",
                    "image": "chocolate-chips.jpg",
                    "consistency": "SOLID",
                    "name": "chocolate chips",
                    "nameClean": "mini chocolate chips",
                    "original": "1 cup mini chocolate chips",
                    "originalName": "mini chocolate chips",
                    "amount": 1.0,
                    "unit": "cup",
                    "meta": ["mini"],
                    "measures": {
                        "us": {"amount": 1.0, "unitShort": "cup", "unitLong": "cup"},
                        "metric": {
                            "amount": 236.588,
                            "unitShort": "ml",
                            "unitLong": "milliliters",
                        },
                    },
                },
                {
                    "id": 2010,
                    "aisle": "Spices and Seasonings",
                    "image": "cinnamon.jpg",
                    "consistency": "SOLID",
                    "name": "cinnamon",
                    "nameClean": "cinnamon",
                    "original": "1/2 teaspoon cinnamon",
                    "originalName": "cinnamon",
                    "amount": 0.5,
                    "unit": "teaspoon",
                    "meta": [],
                    "measures": {
                        "us": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons",
                        },
                        "metric": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons",
                        },
                    },
                },
                {
                    "id": 10116098,
                    "aisle": "Nut butters, Jams, and Honey",
                    "image": "peanut-butter.png",
                    "consistency": "SOLID",
                    "name": "creamy peanut butter",
                    "nameClean": "creamy peanut butter",
                    "original": "1/2 cup creamy peanut butter",
                    "originalName": "creamy peanut butter",
                    "amount": 0.5,
                    "unit": "cup",
                    "meta": [],
                    "measures": {
                        "us": {"amount": 0.5, "unitShort": "cups", "unitLong": "cups"},
                        "metric": {
                            "amount": 118.294,
                            "unitShort": "ml",
                            "unitLong": "milliliters",
                        },
                    },
                },
                {
                    "id": 1123,
                    "aisle": "Milk, Eggs, Other Dairy",
                    "image": "egg.png",
                    "consistency": "SOLID",
                    "name": "egg",
                    "nameClean": "egg",
                    "original": "1 Large egg",
                    "originalName": "Large egg",
                    "amount": 1.0,
                    "unit": "",
                    "meta": [],
                    "measures": {
                        "us": {"amount": 1.0, "unitShort": "", "unitLong": ""},
                        "metric": {"amount": 1.0, "unitShort": "", "unitLong": ""},
                    },
                },
                {
                    "id": 20081,
                    "aisle": "Baking",
                    "image": "flour.png",
                    "consistency": "SOLID",
                    "name": "flour",
                    "nameClean": "wheat flour",
                    "original": "1 1/4 cup flour, unbleached or all-purpose",
                    "originalName": "flour, unbleached or all-purpose",
                    "amount": 1.25,
                    "unit": "cup",
                    "meta": ["all-purpose"],
                    "measures": {
                        "us": {"amount": 1.25, "unitShort": "cups", "unitLong": "cups"},
                        "metric": {
                            "amount": 295.735,
                            "unitShort": "ml",
                            "unitLong": "milliliters",
                        },
                    },
                },
                {
                    "id": 19335,
                    "aisle": "Baking",
                    "image": "sugar-in-bowl.png",
                    "consistency": "SOLID",
                    "name": "granulated sugar",
                    "nameClean": "sugar",
                    "original": "1 1/4 cup granulated sugar",
                    "originalName": "granulated sugar",
                    "amount": 1.25,
                    "unit": "cup",
                    "meta": [],
                    "measures": {
                        "us": {"amount": 1.25, "unitShort": "cups", "unitLong": "cups"},
                        "metric": {
                            "amount": 295.735,
                            "unitShort": "ml",
                            "unitLong": "milliliters",
                        },
                    },
                },
                {
                    "id": 2047,
                    "aisle": "Spices and Seasonings",
                    "image": "salt.jpg",
                    "consistency": "SOLID",
                    "name": "salt",
                    "nameClean": "table salt",
                    "original": "1/2 teaspoon salt",
                    "originalName": "salt",
                    "amount": 0.5,
                    "unit": "teaspoon",
                    "meta": [],
                    "measures": {
                        "us": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons",
                        },
                        "metric": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons",
                        },
                    },
                },
                {
                    "id": 2050,
                    "aisle": "Baking",
                    "image": "vanilla-extract.jpg",
                    "consistency": "LIQUID",
                    "name": "vanilla",
                    "nameClean": "vanilla extract",
                    "original": "1 teaspoon vanilla",
                    "originalName": "vanilla",
                    "amount": 1.0,
                    "unit": "teaspoon",
                    "meta": [],
                    "measures": {
                        "us": {
                            "amount": 1.0,
                            "unitShort": "tsp",
                            "unitLong": "teaspoon",
                        },
                        "metric": {
                            "amount": 1.0,
                            "unitShort": "tsp",
                            "unitLong": "teaspoon",
                        },
                    },
                },
            ],
            "id": 638940,
            "title": "Chocolate Chip Peanut Butter Banana Cookies",
            "readyInMinutes": 45,
            "servings": 24,
            "sourceUrl": "http://www.foodista.com/recipe/RZGVSKMQ/chocolate-chip-peanut-butter-banana-cookies",
            "image": "https://spoonacular.com/recipeImages/638940-556x370.jpg",
            "imageType": "jpg",
            "summary": 'The recipe Chocolate Chip Peanut Butter Banana Cookies could satisfy your Southern craving in about <b>45 minutes</b>. For <b>15 cents per serving</b>, this recipe <b>covers 3%</b> of your daily requirements of vitamins and minerals. This recipe makes 24 servings with <b>167 calories</b>, <b>3g of protein</b>, and <b>5g of fat</b> each. If you have baking powder, baking soda, vanilla, and a few other ingredients on hand, you can make it. This recipe from Foodista has 81 fans. All things considered, we decided this recipe <b>deserves a spoonacular score of 17%</b>. This score is not so amazing. Try <a href="https://spoonacular.com/recipes/peanut-butter-banana-chocolate-chip-cookies-712944">Peanut Butter Banana Chocolate Chip Cookies</a>, <a href="https://spoonacular.com/recipes/chocolate-chip-peanut-butter-banana-cookies-684339">Chocolate Chip Peanut Butter Banana Cookies</a>, and <a href="https://spoonacular.com/recipes/peanut-butter-chocolate-and-banana-chip-cookies-655260">Peanut Butter Chocolate and Banana Chip Cookies</a> for similar recipes.',
            "cuisines": ["Southern"],
            "dishTypes": [
                "antipasti",
                "starter",
                "snack",
                "appetizer",
                "antipasto",
                "hor d'oeuvre",
            ],
            "diets": [],
            "occasions": [],
            "instructions": "<ol><li>Preheat oven to 350 degrees.</li><li>In a large bowl, mash 2 ripened bananas.</li><li>Add butter, peanut butter, both sugars, egg, vanilla and stir.</li><li>In a separate bowl, whisk together flour, baking powder, baking soda, cinnamon and salt.</li><li>Add dry ingredients to banana mixture and stir until combined (do not stir this to death!)</li><li>Add mini chocolate chips and briefly stir.</li><li>Drop by large spoonful onto parchment lined baking sheet.</li><li>In a small bowl, pour 1/4 cup of sugar and 1/2 tsp of cinnamon and stir.  Sprinkle over unbaked cookies.</li><li>Bake for 10-12 minutes or until slightly golden brown.  My oven is hot, and only needs 10 minutes.  </li></ol>",
            "analyzedInstructions": [
                {
                    "name": "",
                    "steps": [
                        {
                            "number": 1,
                            "step": "Preheat oven to 350 degrees.In a large bowl, mash 2 ripened bananas.",
                            "ingredients": [
                                {
                                    "id": 9040,
                                    "name": "banana",
                                    "localizedName": "banana",
                                    "image": "bananas.jpg",
                                }
                            ],
                            "equipment": [
                                {
                                    "id": 404783,
                                    "name": "bowl",
                                    "localizedName": "bowl",
                                    "image": "bowl.jpg",
                                },
                                {
                                    "id": 404784,
                                    "name": "oven",
                                    "localizedName": "oven",
                                    "image": "oven.jpg",
                                },
                            ],
                        },
                        {
                            "number": 2,
                            "step": "Add butter, peanut butter, both sugars, egg, vanilla and stir.In a separate bowl, whisk together flour, baking powder, baking soda, cinnamon and salt.",
                            "ingredients": [
                                {
                                    "id": 18369,
                                    "name": "baking powder",
                                    "localizedName": "baking powder",
                                    "image": "white-powder.jpg",
                                },
                                {
                                    "id": 16098,
                                    "name": "peanut butter",
                                    "localizedName": "peanut butter",
                                    "image": "peanut-butter.png",
                                },
                                {
                                    "id": 18372,
                                    "name": "baking soda",
                                    "localizedName": "baking soda",
                                    "image": "white-powder.jpg",
                                },
                                {
                                    "id": 2010,
                                    "name": "cinnamon",
                                    "localizedName": "cinnamon",
                                    "image": "cinnamon.jpg",
                                },
                                {
                                    "id": 1052050,
                                    "name": "vanilla",
                                    "localizedName": "vanilla",
                                    "image": "vanilla.jpg",
                                },
                                {
                                    "id": 1001,
                                    "name": "butter",
                                    "localizedName": "butter",
                                    "image": "butter-sliced.jpg",
                                },
                                {
                                    "id": 20081,
                                    "name": "all purpose flour",
                                    "localizedName": "all purpose flour",
                                    "image": "flour.png",
                                },
                                {
                                    "id": 2047,
                                    "name": "salt",
                                    "localizedName": "salt",
                                    "image": "salt.jpg",
                                },
                                {
                                    "id": 1123,
                                    "name": "egg",
                                    "localizedName": "egg",
                                    "image": "egg.png",
                                },
                            ],
                            "equipment": [
                                {
                                    "id": 404661,
                                    "name": "whisk",
                                    "localizedName": "whisk",
                                    "image": "whisk.png",
                                },
                                {
                                    "id": 404783,
                                    "name": "bowl",
                                    "localizedName": "bowl",
                                    "image": "bowl.jpg",
                                },
                            ],
                        },
                        {
                            "number": 3,
                            "step": "Add dry ingredients to banana mixture and stir until combined (do not stir this to death!)",
                            "ingredients": [
                                {
                                    "id": 9040,
                                    "name": "banana",
                                    "localizedName": "banana",
                                    "image": "bananas.jpg",
                                }
                            ],
                            "equipment": [],
                        },
                        {
                            "number": 4,
                            "step": "Add mini chocolate chips and briefly stir.Drop by large spoonful onto parchment lined baking sheet.In a small bowl, pour 1/4 cup of sugar and 1/2 tsp of cinnamon and stir.",
                            "ingredients": [
                                {
                                    "id": 10019146,
                                    "name": "mini chocolate chips",
                                    "localizedName": "mini chocolate chips",
                                    "image": "chocolate-chips.jpg",
                                },
                                {
                                    "id": 2010,
                                    "name": "cinnamon",
                                    "localizedName": "cinnamon",
                                    "image": "cinnamon.jpg",
                                },
                                {
                                    "id": 19335,
                                    "name": "sugar",
                                    "localizedName": "sugar",
                                    "image": "sugar-in-bowl.png",
                                },
                            ],
                            "equipment": [
                                {
                                    "id": 404727,
                                    "name": "baking sheet",
                                    "localizedName": "baking sheet",
                                    "image": "baking-sheet.jpg",
                                },
                                {
                                    "id": 404783,
                                    "name": "bowl",
                                    "localizedName": "bowl",
                                    "image": "bowl.jpg",
                                },
                            ],
                        },
                        {
                            "number": 5,
                            "step": "Sprinkle over unbaked cookies.",
                            "ingredients": [
                                {
                                    "id": 10118192,
                                    "name": "cookies",
                                    "localizedName": "cookies",
                                    "image": "shortbread-cookies.jpg",
                                }
                            ],
                            "equipment": [],
                        },
                        {
                            "number": 6,
                            "step": "Bake for 10-12 minutes or until slightly golden brown.  My oven is hot, and only needs 10 minutes.",
                            "ingredients": [],
                            "equipment": [
                                {
                                    "id": 404784,
                                    "name": "oven",
                                    "localizedName": "oven",
                                    "image": "oven.jpg",
                                }
                            ],
                            "length": {"number": 22, "unit": "minutes"},
                        },
                    ],
                }
            ],
            "originalId": None,
            "spoonacularSourceUrl": "https://spoonacular.com/chocolate-chip-peanut-butter-banana-cookies-638940",
        }
    ]
}

#----------------------------------------------------------------------------------------------------------------------------------

sampleapi2 = {
    "results": [
        {
            "id": 716426,
            "title": "Cauliflower, Brown Rice, and Vegetable Fried Rice",
            "image": "https://spoonacular.com/recipeImages/716426-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 715594,
            "title": "Homemade Garlic and Basil French Fries",
            "image": "https://spoonacular.com/recipeImages/715594-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 715497,
            "title": "Berry Banana Breakfast Smoothie",
            "image": "https://spoonacular.com/recipeImages/715497-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 644387,
            "title": "Garlicky Kale",
            "image": "https://spoonacular.com/recipeImages/644387-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 782601,
            "title": "Red Kidney Bean Jambalaya",
            "image": "https://spoonacular.com/recipeImages/782601-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 794349,
            "title": "Broccoli and Chickpea Rice Salad",
            "image": "https://spoonacular.com/recipeImages/794349-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 766453,
            "title": "Hummus and Za'atar",
            "image": "https://spoonacular.com/recipeImages/766453-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 716627,
            "title": "Easy Homemade Rice and Beans",
            "image": "https://spoonacular.com/recipeImages/716627-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 640941,
            "title": "Crunchy Brussels Sprouts Side Dish",
            "image": "https://spoonacular.com/recipeImages/640941-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 798400,
            "title": "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
            "image": "https://spoonacular.com/recipeImages/798400-312x231.jpg",
            "imageType": "jpg",
        },
    ],
    "offset": 0,
    "number": 10,
    "totalResults": 2217,
}

sampleapi3 = {
    "results": [
        {
            "id": 716426,
            "title": "Cauliflower, Brown Rice, and Vegetable Fried Rice",
            "image": "https://spoonacular.com/recipeImages/716426-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 715594,
            "title": "Homemade Garlic and Basil French Fries",
            "image": "https://spoonacular.com/recipeImages/715594-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 715497,
            "title": "Berry Banana Breakfast Smoothie",
            "image": "https://spoonacular.com/recipeImages/715497-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 644387,
            "title": "Garlicky Kale",
            "image": "https://spoonacular.com/recipeImages/644387-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 716268,
            "title": "African Chicken Peanut Stew",
            "image": "https://spoonacular.com/recipeImages/716268-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 716381,
            "title": "Nigerian Snail Stew",
            "image": "https://spoonacular.com/recipeImages/716381-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 782601,
            "title": "Red Kidney Bean Jambalaya",
            "image": "https://spoonacular.com/recipeImages/782601-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 794349,
            "title": "Broccoli and Chickpea Rice Salad",
            "image": "https://spoonacular.com/recipeImages/794349-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 715446,
            "title": "Slow Cooker Beef Stew",
            "image": "https://spoonacular.com/recipeImages/715446-312x231.jpg",
            "imageType": "jpg",
        },
        {
            "id": 715415,
            "title": "Red Lentil Soup with Chicken and Turnips",
            "image": "https://spoonacular.com/recipeImages/715415-312x231.jpg",
            "imageType": "jpg",
        },
    ],
    "offset": 0,
    "number": 10,
    "totalResults": 5224,
}
