# Generated by Django 4.1.1 on 2022-10-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0004_rename_comments_comment_comment_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
