# Generated by Django 4.1.1 on 2022-10-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0008_remove_subscribe_subscribed_subscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
