# Generated by Django 4.1.1 on 2022-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0005_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
    ]
