# Generated by Django 4.1.1 on 2022-10-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0006_favorite_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
