# Generated by Django 4.1.1 on 2022-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0007_remove_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
